version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: Hazentra
      POSTGRES_PASSWORD: Shivan0711@
      POSTGRES_DB: postgresql://postgres.vhheymbeakhuxfxdkutx:Shivan0711%40@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      ALLOWED_ORIGINS: "http://localhost:8000"
    volumes:
      - ./backend/weights:/app/weights

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres.vhheymbeakhuxfxdkutx:Shivan0711%40@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
      NEXT_PUBLIC_MODEL_API_URL: "http://localhost:3000"
    depends_on:
      - db
      - backend

volumes:
  db_data:
